name: Build luci-app-vnt2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [openwrt-24.10, SNAPSHOT]
    steps:
      - uses: actions/checkout@v4
      - uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: x86_64-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-vnt2
          NO_REFRESH_CHECK: true
      - uses: actions/upload-artifact@v4
        with:
          name: ipk-${{ matrix.sdk }}
          path: bin/packages/x86_64/packages_ci/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - id: ver
        run: echo "tag=v$(awk -F':=' '/PKG_VERSION/{print $2}' luci-app-vnt2/Makefile)" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          path: ipks
          merge-multiple: true
      #- uses: softprops/action-gh-release@v2
        #with:
          #tag_name: ${{ steps.ver.outputs.tag }}
          #name: luci-app-vnt2 ${{ steps.ver.outputs.tag }}
          #files: ipks/*
          #make_latest: true
